# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

jms_serializer:
    metadata:
        directories:
            sylius-promotion:
                namespace_prefix: "Sylius\\Component\\Promotion"
                path: "@SyliusPromotionBundle/Resources/config/serializer"

sylius_promotion:

    catalog_promotion_action:
        validation_groups:
            percentage_discount:
                - 'sylius'
                - 'sylius_catalog_promotion_action_percentage_discount'
